version: '3.8'

services:
  s3_app:
    container_name: s3_app
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_USE_SSL: "false"
      JWT_SECRET: ${JWT_SECRET}
      DEBUG: ${DEBUG}
    ports:
      - "8080:8080"
    depends_on:
      - s3_postgres
    networks:
      - app-network
  s3_postgres:
    container_name: s3_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: s3_postgres
      POSTGRES_DB: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  miniodata: